"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import { useAuth } from "@/contexts/AuthContext";
import { parseTomanToRial } from "@/lib/money";
import { normalizeDigits } from "@/lib/phone";

interface RoomRow {
  id: string; title: string; description: string | null; region: "global"|"garena"; map: string; teamMode: "solo"|"duo"|"squad"; perspective: string;
  status: string; isPublished: boolean; capacity: number; registeredCount: number; entryFeeRial: string; serviceFeeRial: string; prizeBudgetRial: string;
  rewardConfig: { perKillRial?: string; participationRial?: string; maxKillsPerEntry?: number; placementRules?: Array<{ from:number;to:number;amountRial:string }> };
  referralRateBps?: number; minRankPoints: number; requiresRecording: boolean; startsAt: string; endsAt: string|null; checkInOpensAt: string|null; checkInClosesAt: string|null; credentialsRevealAt: string|null;
}
interface DetailEntry { id?: string; displayName: string; codUsername: string; status: string; checkedIn: boolean; kills?: number|null; placement?: number|null; resultStatus?: string; }
interface DetailRoom extends RoomRow { roomCode:string|null;roomPassword:string|null;officialJoinUrl:string|null;rules:string|null;rulesVersion:string;entries:DetailEntry[];evidenceCount:number; }

const statusNext: Record<string,string[]> = {
  draft:["draft","registration","cancelled"], registration:["registration","check_in","cancelled"], check_in:["check_in","lobby_open","cancelled"],
  lobby_open:["lobby_open","in_progress","cancelled"], in_progress:["in_progress","settling","cancelled"], settling:["settling","completed","in_progress","cancelled"], completed:["completed"], cancelled:["cancelled"],
};
const statusFa: Record<string,string> = { draft:"پیش‌نویس",registration:"ثبت‌نام",check_in:"Check-in",lobby_open:"Lobby باز",in_progress:"در اجرا",settling:"داوری",completed:"تکمیل",cancelled:"لغو" };
function tomanToRial(value: string|number) { return parseTomanToRial(String(value || "0")).toString(); }
function rialToToman(value: string|number|null|undefined) { try{return String(BigInt(String(value||0))/BigInt(10));}catch{return "0";} }
function localDate(value?:string|null){if(!value)return"";const d=new Date(value);if(Number.isNaN(d.getTime()))return"";return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function iso(value:string){return value?new Date(value).toISOString():null;}

const initialForm = {
  id:"",title:"",description:"",region:"global" as "global"|"garena",map:"isolated",teamMode:"solo" as "solo"|"duo"|"squad",perspective:"tpp",status:"draft",isPublished:false,
  capacity:40,entryFeeToman:"0",serviceFeeToman:"0",prizeBudgetToman:"0",referralPercent:"20",perKillToman:"0",participationToman:"0",maxKillsPerEntry:40,
  firstToman:"0",secondToman:"0",thirdToman:"0",minRankPoints:0,requiresRecording:true,rulesVersion:"cod-beta-1",rules:"",
  roomCode:"",roomPassword:"",officialJoinUrl:"",checkInOpensAt:"",checkInClosesAt:"",credentialsRevealAt:"",startsAt:"",endsAt:"",
};

export default function AdminCodArenaPage(){
  const {user,loading:authLoading}=useAuth(); const router=useRouter();
  const [rooms,setRooms]=useState<RoomRow[]>([]); const [loading,setLoading]=useState(true); const [live,setLive]=useState(false); const [form,setForm]=useState(initialForm); const [showForm,setShowForm]=useState(false);
  const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [selected,setSelected]=useState<DetailRoom|null>(null);
  const [results,setResults]=useState<Record<string,{kills:string;placement:string}>>({}); const [evidenceConfirmed,setEvidenceConfirmed]=useState(false); const [staff,setStaff]=useState({identifier:"",role:"roomer"});
  const isAdmin=user?.role==="admin"||user?.role==="super_admin";

  useEffect(()=>{if(!authLoading&&(!user||!isAdmin))router.push("/");},[authLoading,user,isAdmin,router]);
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin/cod/rooms",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setRooms(d.rooms||[]);setLive(Boolean(d.live));}catch(e){setError(e instanceof Error?e.message:"بارگذاری نشد");}finally{setLoading(false);}},[]);
  useEffect(()=>{if(isAdmin)load();},[isAdmin,load]);

  const payload=useMemo(()=>({
    ...form,
    entryFeeRial:tomanToRial(form.entryFeeToman),serviceFeeRial:tomanToRial(form.serviceFeeToman),prizeBudgetRial:tomanToRial(form.prizeBudgetToman),referralRateBps:Math.round(Number(normalizeDigits(String(form.referralPercent||0)).replace("٫","."))*100),
    rewardConfig:{perKillRial:tomanToRial(form.perKillToman),participationRial:tomanToRial(form.participationToman),maxKillsPerEntry:Number(form.maxKillsPerEntry),placementRules:[
      ...(Number(form.firstToman)>0?[{from:1,to:1,amountRial:tomanToRial(form.firstToman)}]:[]),...(Number(form.secondToman)>0?[{from:2,to:2,amountRial:tomanToRial(form.secondToman)}]:[]),...(Number(form.thirdToman)>0?[{from:3,to:3,amountRial:tomanToRial(form.thirdToman)}]:[]),
    ]},
    startsAt:iso(form.startsAt),endsAt:iso(form.endsAt),checkInOpensAt:iso(form.checkInOpensAt),checkInClosesAt:iso(form.checkInClosesAt),credentialsRevealAt:iso(form.credentialsRevealAt),
  }),[form]);

  function begin(){setForm({...initialForm,startsAt:localDate(new Date(Date.now()+24*60*60_000).toISOString())});setShowForm(true);setSelected(null);setError("");}
  async function edit(room:RoomRow){
    setError("");
    try {
      const response=await fetch(`/api/cod/rooms/${room.id}`,{cache:"no-store"});
      const data=await response.json();
      if(!response.ok)throw new Error(data.error||"اطلاعات روم دریافت نشد");
      const full=data.room as DetailRoom;
      setForm({...initialForm,id:full.id,title:full.title,description:full.description||"",region:full.region,map:full.map,teamMode:full.teamMode,perspective:full.perspective,status:full.status,isPublished:full.isPublished,capacity:full.capacity,entryFeeToman:rialToToman(full.entryFeeRial),serviceFeeToman:rialToToman(full.serviceFeeRial),prizeBudgetToman:rialToToman(full.prizeBudgetRial),referralPercent:String(Number(full.referralRateBps||0)/100),perKillToman:rialToToman(full.rewardConfig?.perKillRial),participationToman:rialToToman(full.rewardConfig?.participationRial),maxKillsPerEntry:Number(full.rewardConfig?.maxKillsPerEntry||40),firstToman:rialToToman(full.rewardConfig?.placementRules?.find(x=>x.from===1)?.amountRial),secondToman:rialToToman(full.rewardConfig?.placementRules?.find(x=>x.from===2)?.amountRial),thirdToman:rialToToman(full.rewardConfig?.placementRules?.find(x=>x.from===3)?.amountRial),minRankPoints:full.minRankPoints,requiresRecording:full.requiresRecording,rulesVersion:full.rulesVersion||"cod-beta-1",rules:full.rules||"",roomCode:full.roomCode||"",roomPassword:full.roomPassword||"",officialJoinUrl:full.officialJoinUrl||"",startsAt:localDate(full.startsAt),endsAt:localDate(full.endsAt),checkInOpensAt:localDate(full.checkInOpensAt),checkInClosesAt:localDate(full.checkInClosesAt),credentialsRevealAt:localDate(full.credentialsRevealAt)});
      setShowForm(true);setSelected(null);scrollTo({top:0,behavior:"smooth"});
    } catch(e){setError(e instanceof Error?e.message:"اطلاعات روم دریافت نشد");}
  }
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const r=await fetch("/api/admin/cod/rooms",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"ذخیره نشد");setMessage(form.id?"روم به‌روزرسانی شد":"روم Private Beta ساخته شد");setShowForm(false);setForm(initialForm);await load();}catch(e){setError(e instanceof Error?e.message:"ذخیره نشد");}finally{setSaving(false);}}
  async function remove(id:string){if(!confirm("فقط Draft خالی قابل حذف است. حذف شود؟"))return;const r=await fetch("/api/admin/cod/rooms",{method:"DELETE",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setError(d.error||"حذف نشد");return;}load();}
  async function openOps(id:string){setError("");const r=await fetch(`/api/cod/rooms/${id}`,{cache:"no-store"});const d=await r.json();if(!r.ok){setError(d.error||"دریافت نشد");return;}setSelected(d.room);const next:Record<string,{kills:string;placement:string}>={};for(const e of d.room.entries||[])if(e.id)next[e.id]={kills:String(e.kills||0),placement:e.placement?String(e.placement):""};setResults(next);setEvidenceConfirmed(false);setShowForm(false);}
  async function settle(){if(!selected||!confirm("نتایج نهایی و روم تسویه شود؟ در Beta فقط Shadow ثبت می‌شود."))return;setSaving(true);setError("");try{const eligibleIds=new Set(selected.entries.filter(entry=>entry.id&&entry.checkedIn).map(entry=>entry.id));const body={evidenceConfirmed,results:Object.entries(results).filter(([entryId])=>eligibleIds.has(entryId)).map(([entryId,v])=>({entryId,kills:Number(v.kills||0),placement:v.placement?Number(v.placement):null}))};const r=await fetch(`/api/admin/cod/rooms/${selected.id}/settle`,{method:"POST",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"تسویه نشد");setMessage(`تسویه ${d.settlement.entryCount} بازیکن با موفقیت در ${d.settlement.live?"Live":"Shadow"} ثبت شد.`);setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:"تسویه نشد");}finally{setSaving(false);}}
  async function assignStaff(){if(!selected||!staff.identifier)return;const r=await fetch(`/api/admin/cod/rooms/${selected.id}/staff`,{method:"POST",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify(staff)});const d=await r.json();if(!r.ok){setError(d.error||"تخصیص انجام نشد");return;}setMessage("عامل اجرایی به روم اضافه شد");setStaff({identifier:"",role:"roomer"});}
  if(authLoading||!isAdmin)return null;

  const input="w-full rounded-xl border border-white/10 bg-black/35 px-3 py-3 text-sm outline-none focus:border-orange-400";
  return <div className="min-h-screen bg-[#070707] text-white"><Navbar/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-7" dir="rtl">
    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div><Link href="/admin" className="text-xs text-gray-500">← داشبورد</Link><h1 className="text-3xl font-black mt-3">🎯 مرکز عملیات COD Arena</h1><p className="text-xs text-gray-500 mt-2">ساخت روم، چرخه Lobby، عوامل اجرایی، مدرک، نتیجه، رنک، جایزه و رفرال</p></div><div className="flex gap-2"><Link href="/cod-arena" className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black">نمای بازیکن</Link><button onClick={begin} className="rounded-xl bg-orange-500 text-black px-5 py-3 text-xs font-black">+ روم جدید</button></div></div>
    <div className={`mt-5 rounded-2xl border p-4 text-xs ${live?"border-red-500/30 bg-red-500/10 text-red-300":"border-emerald-500/20 bg-emerald-500/10 text-emerald-300"}`}>{live?"⚠️ COD_ARENA_LIVE روشن است؛ عملیات مالی واقعی فعال است.":"✅ Private Beta: کسر وجه، جایزه و رفرال فقط Shadow هستند."}</div>
    {error&&<div className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}{message&&<div className="mt-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-300">{message}</div>}

    {showForm&&<form onSubmit={save} className="mt-6 rounded-[2rem] border border-orange-500/20 bg-orange-950/10 p-5 sm:p-7 space-y-6">
      <div className="flex justify-between"><h2 className="text-xl font-black">{form.id?"ویرایش روم":"ساخت روم Private Beta"}</h2><button type="button" onClick={()=>setShowForm(false)} className="text-gray-500">✕</button></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><label className="lg:col-span-2 text-xs text-gray-400">عنوان<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">ریجن<select value={form.region} onChange={e=>setForm({...form,region:e.target.value as "global"|"garena"})} className={`${input} mt-1`}><option value="global">Global</option><option value="garena">Garena</option></select></label><label className="text-xs text-gray-400">حالت<select value={form.teamMode} onChange={e=>setForm({...form,teamMode:e.target.value as "solo"|"duo"|"squad"})} className={`${input} mt-1`}><option value="solo">Solo</option><option value="duo">Duo</option><option value="squad">Squad</option></select></label><label className="text-xs text-gray-400">Map<input value={form.map} onChange={e=>setForm({...form,map:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">Perspective<select value={form.perspective} onChange={e=>setForm({...form,perspective:e.target.value})} className={`${input} mt-1`}><option value="tpp">TPP</option><option value="fpp">FPP</option></select></label><label className="text-xs text-gray-400">ظرفیت<input type="number" min={2} max={100} value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">حداقل RP<input type="number" min={0} value={form.minRankPoints} onChange={e=>setForm({...form,minRankPoints:Number(e.target.value)})} className={`${input} mt-1`}/></label></div>
      <label className="block text-xs text-gray-400">توضیحات<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className={`${input} mt-1`}/></label>
      <div><h3 className="font-black text-orange-300 mb-3">اقتصاد روم — تومان</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[["ورودی","entryFeeToman"],["کارمزد Gament","serviceFeeToman"],["بودجه جایزه","prizeBudgetToman"],["رفرال از کارمزد %","referralPercent"],["هر Kill","perKillToman"],["جایزه حضور","participationToman"],["نفر اول","firstToman"],["نفر دوم","secondToman"],["نفر سوم","thirdToman"]].map(([label,key])=><label key={key} className="text-xs text-gray-400">{label}<input inputMode="numeric" value={String(form[key as keyof typeof form])} onChange={e=>setForm({...form,[key]:e.target.value})} className={`${input} mt-1`}/></label>)}<label className="text-xs text-gray-400">سقف Kill<input type="number" min={1} max={100} value={form.maxKillsPerEntry} onChange={e=>setForm({...form,maxKillsPerEntry:Number(e.target.value)})} className={`${input} mt-1`}/></label></div></div>
      <div><h3 className="font-black text-orange-300 mb-3">زمان‌بندی</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-xs text-gray-400">شروع روم<input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">شروع Check-in<input type="datetime-local" value={form.checkInOpensAt} onChange={e=>setForm({...form,checkInOpensAt:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">پایان Check-in<input type="datetime-local" value={form.checkInClosesAt} onChange={e=>setForm({...form,checkInClosesAt:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">نمایش کد و لینک<input type="datetime-local" value={form.credentialsRevealAt} onChange={e=>setForm({...form,credentialsRevealAt:e.target.value})} className={`${input} mt-1`}/></label><label className="text-xs text-gray-400">پایان تقریبی<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} className={`${input} mt-1`}/></label></div></div>
      <div><h3 className="font-black text-orange-300 mb-3">اطلاعات محرمانه Lobby</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-xs text-gray-400">Room Code<input value={form.roomCode} onChange={e=>setForm({...form,roomCode:e.target.value})} className={`${input} mt-1`} dir="ltr"/></label><label className="text-xs text-gray-400">Password<input value={form.roomPassword} onChange={e=>setForm({...form,roomPassword:e.target.value})} className={`${input} mt-1`} dir="ltr"/></label><label className="text-xs text-gray-400">لینک رسمی COD<input value={form.officialJoinUrl} onChange={e=>setForm({...form,officialJoinUrl:e.target.value})} className={`${input} mt-1`} dir="ltr"/></label></div></div>
      <label className="block text-xs text-gray-400">قوانین<textarea value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})} rows={6} className={`${input} mt-1`}/></label>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-xs text-gray-400">وضعیت<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={`${input} mt-1`}>{(statusNext[form.status]||[form.status]).map(x=><option key={x} value={x}>{statusFa[x]||x}</option>)}</select></label><label className="flex items-center gap-2 text-xs mt-7"><input type="checkbox" checked={form.requiresRecording} onChange={e=>setForm({...form,requiresRecording:e.target.checked})}/> رکورد بازیکنان الزامی</label><label className="flex items-center gap-2 text-xs mt-7"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> نمایش در COD Arena</label></div>
      <button disabled={saving} className="rounded-2xl bg-orange-500 text-black px-8 py-3.5 text-sm font-black disabled:opacity-50">{saving?"در حال ذخیره...":"ذخیره امن روم"}</button>
    </form>}

    {selected&&<section className="mt-6 rounded-[2rem] border border-purple-500/20 bg-purple-950/10 p-5 sm:p-7"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-black">عملیات و تسویه: {selected.title}</h2><p className="text-xs text-gray-500 mt-2">مدارک: {selected.evidenceCount} • بازیکنان: {selected.entries.length}</p></div><button onClick={()=>setSelected(null)}>✕</button></div>
      <div className="grid grid-cols-1 sm:grid-cols-[1fr_150px_auto] gap-2 mt-5"><input value={staff.identifier} onChange={e=>setStaff({...staff,identifier:e.target.value})} placeholder="Username / Gament ID عامل اجرایی" className={input}/><select value={staff.role} onChange={e=>setStaff({...staff,role:e.target.value})} className={input}><option value="roomer">Roomer</option><option value="spectator">Spectator</option><option value="judge">Judge</option></select><button onClick={assignStaff} className="rounded-xl bg-purple-600 px-4 text-xs font-black">تخصیص</button></div>
      <div className="overflow-x-auto mt-6"><table className="w-full min-w-[650px] text-xs"><thead className="text-gray-500"><tr><th className="text-right p-2">بازیکن</th><th className="p-2">Check-in</th><th className="p-2">Kill</th><th className="p-2">Placement</th><th className="p-2">وضعیت</th></tr></thead><tbody>{selected.entries.map(e=>e.id&&<tr key={e.id} className="border-t border-white/5"><td className="p-2"><b>{e.displayName}</b><div className="text-gray-600" dir="ltr">{e.codUsername}</div></td><td className="p-2 text-center">{e.checkedIn?"✅":"—"}</td><td className="p-2"><input type="number" min={0} max={100} disabled={!e.checkedIn} value={results[e.id]?.kills||"0"} onChange={x=>setResults({...results,[e.id!]:{...results[e.id!],kills:x.target.value}})} className="w-20 rounded-lg bg-black/40 border border-white/10 p-2 text-center"/></td><td className="p-2"><input type="number" min={1} max={100} disabled={!e.checkedIn} value={results[e.id]?.placement||""} onChange={x=>setResults({...results,[e.id!]:{...results[e.id!],placement:x.target.value}})} className="w-20 rounded-lg bg-black/40 border border-white/10 p-2 text-center"/></td><td className="p-2 text-center">{e.status}</td></tr>)}</tbody></table></div>
      <label className="flex gap-3 items-start text-xs leading-6 mt-5"><input type="checkbox" checked={evidenceConfirmed} onChange={e=>setEvidenceConfirmed(e.target.checked)} className="mt-1"/><span>رکورد Lobby، Scoreboard و موارد مشکوک را بررسی کرده‌ام و مسئولیت تأیید نتیجه را می‌پذیرم.</span></label><div className="flex flex-wrap gap-2 mt-4"><Link href={`/cod-arena/${selected.id}`} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black">ثبت/مشاهده مدارک</Link><button onClick={settle} disabled={saving||!evidenceConfirmed||!["in_progress","settling"].includes(selected.status)} className="rounded-xl bg-emerald-500 text-black px-5 py-3 text-xs font-black disabled:opacity-40">تسویه نهایی {live?"LIVE":"SHADOW"}</button></div>
    </section>}

    <section className="mt-7"><h2 className="text-xl font-black mb-4">روم‌ها</h2>{loading?<div className="p-10 text-center text-gray-500">در حال بارگذاری...</div>:rooms.length===0?<div className="rounded-3xl border border-white/5 p-10 text-center text-gray-500">هنوز رومی ساخته نشده است.</div>:<div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{rooms.map(room=><article key={room.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="flex justify-between gap-3"><div><div className="flex gap-2 text-[9px]"><span className="rounded-full bg-orange-500/10 text-orange-300 px-2 py-1">{room.region.toUpperCase()}</span><span className="rounded-full bg-white/5 px-2 py-1">{statusFa[room.status]}</span>{!room.isPublished&&<span className="rounded-full bg-gray-500/10 px-2 py-1">مخفی</span>}</div><h3 className="font-black text-lg mt-3">{room.title}</h3><p className="text-[10px] text-gray-500 mt-2">{localDate(room.startsAt).replace("T"," ")} • {room.teamMode.toUpperCase()} • {room.map}</p></div><div className="text-left"><div className="text-xl font-black">{room.registeredCount}/{room.capacity}</div><div className="text-[9px] text-gray-500">بازیکن</div></div></div><div className="flex flex-wrap gap-2 mt-5"><button onClick={()=>edit(room)} className="rounded-xl border border-white/10 px-3 py-2 text-xs">ویرایش</button><button onClick={()=>openOps(room.id)} className="rounded-xl bg-purple-600 px-3 py-2 text-xs font-black">عملیات/نتیجه</button><Link href={`/cod-arena/${room.id}`} className="rounded-xl border border-orange-500/20 text-orange-300 px-3 py-2 text-xs">نمای روم</Link>{room.status==="draft"&&room.registeredCount===0&&<button onClick={()=>remove(room.id)} className="rounded-xl text-red-400 px-3 py-2 text-xs">حذف</button>}</div></article>)}</div>}</section>
  </main></div>;
}
